In [2]:
import numpy as np


In [3]:
a = np.array([1,2,3])
print(a)

b = np.array([[1,2,3],
              [4,5,6]])
print(b)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [4]:
b

array([[1, 2, 3],
       [4, 5, 6]])

# array addition